-- =====================================================================
-- Schema PostgreSQL completo do Painel de Chamadas
--
-- Cria TODAS as tabelas do zero: as do sistema atual (triagem,
-- consultorio, paciente, chamada_painel) já com as colunas extras
-- necessárias pros 27 indicadores de docs/indicadores/indicadores.xlsx,
-- mais a tabela de referência protocolo_tempo. Feito de uma vez só pra
-- não precisar alterar de novo quando o Paciente.java for atualizado.
--
-- IMPORTANTE: o paciente NÃO é deletado ao final do atendimento, apenas
-- anonimizado (nome/cpf/observações apagados). A própria tabela
-- `paciente` é o histórico — não existe tabela separada de atendimentos
-- encerrados.
--
-- Como usar: banco `painel` já deve existir (criado via pgAdmin).
-- Cole este conteúdo no Query Tool do pgAdmin com o banco `painel`
-- selecionado, ou rode via psql:
--   psql -U postgres -d painel -f schema.sql
-- =====================================================================

CREATE TABLE triagem (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero  BIGINT
);

CREATE TABLE consultorio (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero  BIGINT
);

CREATE TABLE paciente (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Colunas que já existem hoje no sistema (H2)
    nome                            VARCHAR(255),
    cpf                             VARCHAR(255),
    triage_notes                    VARCHAR(255),
    status                          VARCHAR(255),  -- AGUARDANDO_TRIAGEM, AGUARDANDO_CONSULTA, CHAMADO, FINALIZADO, DESISTENCIA
    risco                           VARCHAR(255),  -- VERMELHO, LARANJA, AMARELO, VERDE, AZUL, NAO_CLASSIFICADO
    tipo                            VARCHAR(255),  -- CLINICO, PSIQUIATRICO, SAMU
    triagem_id                      BIGINT REFERENCES triagem (id),
    consultorio_id                  BIGINT REFERENCES consultorio (id),
    chegada_at                      TIMESTAMP,   -- abriu a ficha no NAC
    classified_at                   TIMESTAMP,   -- terminou a classificação de risco

    -- Colunas novas, pros indicadores do hospital (Paciente.java ainda
    -- não tem esses campos — ficam pendentes até essa parte ser feita)
    chamada_triagem_at              TIMESTAMP,   -- chamado no painel p/ classificação de risco
    chamada_consultorio_at          TIMESTAMP,   -- chamado no painel p/ consultório (início do atendimento médico)
    atendimento_finalizado_at       TIMESTAMP,   -- momento do encerramento (finalizado ou desistência)
    etapa_desistencia               VARCHAR(255) -- AGUARDANDO_TRIAGEM, AGUARDANDO_CONSULTA (só quando status = DESISTENCIA)
);

CREATE INDEX idx_paciente_chegada_at ON paciente (chegada_at);
CREATE INDEX idx_paciente_risco_tipo ON paciente (risco, tipo);
CREATE INDEX idx_paciente_status ON paciente (status);

CREATE TABLE chamada_painel (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id           BIGINT,
    nome_paciente         VARCHAR(255),
    ticket_number         VARCHAR(255),
    tipo                  VARCHAR(255),  -- TRIAGEM, CONSULTORIO
    destino               VARCHAR(255),
    consultorio_id        BIGINT,
    consultorio_numero    BIGINT,
    risco                 VARCHAR(255),
    criada_em             TIMESTAMP
);

-- Tabela de referência (nova): tempo máximo (protocolo) por risco/tipo.
-- Usada só pelos indicadores de "% de atendimento fora do tempo de protocolo".
-- Precisa ser populada manualmente com os tempos definidos pelo hospital.
CREATE TABLE protocolo_tempo (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risco                 VARCHAR(255) NOT NULL,
    tipo                  VARCHAR(255) NOT NULL,
    tempo_maximo_minutos  INTEGER NOT NULL,
    UNIQUE (risco, tipo)
);

-- =====================================================================
-- Mapeamento indicador -> colunas (docs/indicadores/indicadores.xlsx)
-- Todas as consultas abaixo usam a tabela `paciente` diretamente,
-- filtrando status IN ('FINALIZADO', 'DESISTENCIA') pra considerar
-- apenas atendimentos já encerrados.
-- =====================================================================
-- 1  Tempo de Espera p/ Acolhimento/Classificação
--       = chamada_triagem_at - chegada_at
-- 2  Tempo de Espera Classificação até 1º atendimento médico
--       = chamada_consultorio_at - classified_at
-- 3  Tempo de Espera Entrada (NAC) até Atendimento médico
--       = chamada_consultorio_at - chegada_at
-- 4  Nº de pacientes cadastrados
--       = COUNT(*)  -- todos, independente do status
-- 5  Nº total de pacientes classificados
--       = COUNT(*) WHERE classified_at IS NOT NULL
-- 6  Nº total de pacientes atendidos pelo médico
--       = COUNT(*) WHERE status = 'FINALIZADO'
-- 7  % de pacientes Classificados
--       = indicador 5 / indicador 4
-- 8  % de pacientes Atendidos pelo médico
--       = indicador 6 / indicador 4
-- 9-13  Nº total classificados por COR (VERMELHO/AMARELO/LARANJA/VERDE/AZUL)
--       = COUNT(*) WHERE risco = 'X'
-- 14-20 Tempo médio de espera para atendimento por COR (+ tipo CLINICO/PSIQUIATRICO)
--       = AVG(chamada_consultorio_at - classified_at)
--         WHERE risco = 'X' [AND tipo = 'Y']
-- 21-27 % de atendimento fora do tempo de protocolo por COR (+ tipo)
--       = COUNT(*) WHERE risco='X' [AND tipo='Y']
--         AND (chamada_consultorio_at - classified_at)
--             > (SELECT tempo_maximo_minutos FROM protocolo_tempo WHERE risco='X' AND tipo='Y') * interval '1 minute'
--         dividido pelo total do mesmo filtro (indicadores 14-20)
-- =====================================================================
